package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NodeDomain generated by hbm2java
 */
public class NodeDomain  implements java.io.Serializable {


     private long domainId;
     private String domainName;
     private String domainDesc;
     private String domainStatusCd;
     private String domainStatusMsg;
     private Date createdDttm;
     private String createdBy;
     private Date updatedDttm;
     private String updatedBy;
     private Set<NodeAccountTypeXref> nodeAccountTypeXrefs = new HashSet<NodeAccountTypeXref>(0);
     private Set<NodeWebService> nodeWebServices = new HashSet<NodeWebService>(0);
     private Set<NodeOperation> nodeOperations = new HashSet<NodeOperation>(0);

    public NodeDomain() {
    }

	
    public NodeDomain(long domainId, String domainName) {
        this.domainId = domainId;
        this.domainName = domainName;
    }
    public NodeDomain(long domainId, String domainName, String domainDesc, String domainStatusCd, String domainStatusMsg, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy, Set<NodeAccountTypeXref> nodeAccountTypeXrefs, Set<NodeWebService> nodeWebServices, Set<NodeOperation> nodeOperations) {
       this.domainId = domainId;
       this.domainName = domainName;
       this.domainDesc = domainDesc;
       this.domainStatusCd = domainStatusCd;
       this.domainStatusMsg = domainStatusMsg;
       this.createdDttm = createdDttm;
       this.createdBy = createdBy;
       this.updatedDttm = updatedDttm;
       this.updatedBy = updatedBy;
       this.nodeAccountTypeXrefs = nodeAccountTypeXrefs;
       this.nodeWebServices = nodeWebServices;
       this.nodeOperations = nodeOperations;
    }
   
    public long getDomainId() {
        return this.domainId;
    }
    
    public void setDomainId(long domainId) {
        this.domainId = domainId;
    }
    public String getDomainName() {
        return this.domainName;
    }
    
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }
    public String getDomainDesc() {
        return this.domainDesc;
    }
    
    public void setDomainDesc(String domainDesc) {
        this.domainDesc = domainDesc;
    }
    public String getDomainStatusCd() {
        return this.domainStatusCd;
    }
    
    public void setDomainStatusCd(String domainStatusCd) {
        this.domainStatusCd = domainStatusCd;
    }
    public String getDomainStatusMsg() {
        return this.domainStatusMsg;
    }
    
    public void setDomainStatusMsg(String domainStatusMsg) {
        this.domainStatusMsg = domainStatusMsg;
    }
    public Date getCreatedDttm() {
        return this.createdDttm;
    }
    
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }
    
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<NodeAccountTypeXref> getNodeAccountTypeXrefs() {
        return this.nodeAccountTypeXrefs;
    }
    
    public void setNodeAccountTypeXrefs(Set<NodeAccountTypeXref> nodeAccountTypeXrefs) {
        this.nodeAccountTypeXrefs = nodeAccountTypeXrefs;
    }
    public Set<NodeWebService> getNodeWebServices() {
        return this.nodeWebServices;
    }
    
    public void setNodeWebServices(Set<NodeWebService> nodeWebServices) {
        this.nodeWebServices = nodeWebServices;
    }
    public Set<NodeOperation> getNodeOperations() {
        return this.nodeOperations;
    }
    
    public void setNodeOperations(Set<NodeOperation> nodeOperations) {
        this.nodeOperations = nodeOperations;
    }




}


