package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysEmail generated by hbm2java
 */
public class SysEmail  implements java.io.Serializable {


     private long emailId;
     private String emailAddress;
     private String emailType;
     private Character statusCd;
     private Date createdDttm;
     private String createdBy;
     private Date updatedDttm;
     private String updatedBy;
     private Set<SysUserInfo> sysUserInfos = new HashSet<SysUserInfo>(0);

    public SysEmail() {
    }

	
    public SysEmail(long emailId, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy) {
        this.emailId = emailId;
        this.createdDttm = createdDttm;
        this.createdBy = createdBy;
        this.updatedDttm = updatedDttm;
        this.updatedBy = updatedBy;
    }
    public SysEmail(long emailId, String emailAddress, String emailType, Character statusCd, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy, Set<SysUserInfo> sysUserInfos) {
       this.emailId = emailId;
       this.emailAddress = emailAddress;
       this.emailType = emailType;
       this.statusCd = statusCd;
       this.createdDttm = createdDttm;
       this.createdBy = createdBy;
       this.updatedDttm = updatedDttm;
       this.updatedBy = updatedBy;
       this.sysUserInfos = sysUserInfos;
    }
   
    public long getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(long emailId) {
        this.emailId = emailId;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getEmailType() {
        return this.emailType;
    }
    
    public void setEmailType(String emailType) {
        this.emailType = emailType;
    }
    public Character getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(Character statusCd) {
        this.statusCd = statusCd;
    }
    public Date getCreatedDttm() {
        return this.createdDttm;
    }
    
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }
    
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<SysUserInfo> getSysUserInfos() {
        return this.sysUserInfos;
    }
    
    public void setSysUserInfos(Set<SysUserInfo> sysUserInfos) {
        this.sysUserInfos = sysUserInfos;
    }




}


