package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0



/**
 * SysUserAddress generated by hbm2java
 */
public class SysUserAddress  implements java.io.Serializable {


     private SysUserAddressId id;
     private SysUserInfo sysUserInfo;
     private SysAddress sysAddress;
     private String addressTypeCd;

    public SysUserAddress() {
    }

	
    public SysUserAddress(SysUserAddressId id, SysUserInfo sysUserInfo, SysAddress sysAddress) {
        this.id = id;
        this.sysUserInfo = sysUserInfo;
        this.sysAddress = sysAddress;
    }
    public SysUserAddress(SysUserAddressId id, SysUserInfo sysUserInfo, SysAddress sysAddress, String addressTypeCd) {
       this.id = id;
       this.sysUserInfo = sysUserInfo;
       this.sysAddress = sysAddress;
       this.addressTypeCd = addressTypeCd;
    }
   
    public SysUserAddressId getId() {
        return this.id;
    }
    
    public void setId(SysUserAddressId id) {
        this.id = id;
    }
    public SysUserInfo getSysUserInfo() {
        return this.sysUserInfo;
    }
    
    public void setSysUserInfo(SysUserInfo sysUserInfo) {
        this.sysUserInfo = sysUserInfo;
    }
    public SysAddress getSysAddress() {
        return this.sysAddress;
    }
    
    public void setSysAddress(SysAddress sysAddress) {
        this.sysAddress = sysAddress;
    }
    public String getAddressTypeCd() {
        return this.addressTypeCd;
    }
    
    public void setAddressTypeCd(String addressTypeCd) {
        this.addressTypeCd = addressTypeCd;
    }




}


