package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * NodeOperationLogStatus generated by hbm2java
 */
public class NodeOperationLogStatus  implements java.io.Serializable {


     private long operationLogStatusId;
     private NodeOperationLog nodeOperationLog;
     private String statusCd;
     private String message;
     private Date createdDttm;
     private String createdBy;

    public NodeOperationLogStatus() {
    }

	
    public NodeOperationLogStatus(long operationLogStatusId, String createdBy) {
        this.operationLogStatusId = operationLogStatusId;
        this.createdBy = createdBy;
    }
    public NodeOperationLogStatus(long operationLogStatusId, NodeOperationLog nodeOperationLog, String statusCd, String message, Date createdDttm, String createdBy) {
       this.operationLogStatusId = operationLogStatusId;
       this.nodeOperationLog = nodeOperationLog;
       this.statusCd = statusCd;
       this.message = message;
       this.createdDttm = createdDttm;
       this.createdBy = createdBy;
    }
   
    public long getOperationLogStatusId() {
        return this.operationLogStatusId;
    }
    
    public void setOperationLogStatusId(long operationLogStatusId) {
        this.operationLogStatusId = operationLogStatusId;
    }
    public NodeOperationLog getNodeOperationLog() {
        return this.nodeOperationLog;
    }
    
    public void setNodeOperationLog(NodeOperationLog nodeOperationLog) {
        this.nodeOperationLog = nodeOperationLog;
    }
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getCreatedDttm() {
        return this.createdDttm;
    }
    
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


