package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0



/**
 * NodeOperationLogParameterId generated by hbm2java
 */
public class NodeOperationLogParameterId  implements java.io.Serializable {


     private long operationLogId;
     private String parameterName;

    public NodeOperationLogParameterId() {
    }

    public NodeOperationLogParameterId(long operationLogId, String parameterName) {
       this.operationLogId = operationLogId;
       this.parameterName = parameterName;
    }
   
    public long getOperationLogId() {
        return this.operationLogId;
    }
    
    public void setOperationLogId(long operationLogId) {
        this.operationLogId = operationLogId;
    }
    public String getParameterName() {
        return this.parameterName;
    }
    
    public void setParameterName(String parameterName) {
        this.parameterName = parameterName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NodeOperationLogParameterId) ) return false;
		 NodeOperationLogParameterId castOther = ( NodeOperationLogParameterId ) other; 
         
		 return (this.getOperationLogId()==castOther.getOperationLogId())
 && ( (this.getParameterName()==castOther.getParameterName()) || ( this.getParameterName()!=null && castOther.getParameterName()!=null && this.getParameterName().equals(castOther.getParameterName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getOperationLogId();
         result = 37 * result + ( getParameterName() == null ? 0 : this.getParameterName().hashCode() );
         return result;
   }   


}


