package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NodeOperationLog generated by hbm2java
 */
public class NodeOperationLog  implements java.io.Serializable {


     private long operationLogId;
     private NodeOperation nodeOperation;
     private String transId;
     private String userName;
     private String requestorIp;
     private String suppliedTransId;
     private String token;
     private String nodeAddress;
     private String returnUrl;
     private String serviceType;
     private Date startDttm;
     private Date endDttm;
     private String hostName;
     private Date createdDttm;
     private String createdBy;
     private Date updatedDttm;
     private String updatedBy;
     private Set<NodeOperationLogStatus> nodeOperationLogStatuses = new HashSet<NodeOperationLogStatus>(0);
     private Set<NodeOperationLogParameter> nodeOperationLogParameters = new HashSet<NodeOperationLogParameter>(0);

    public NodeOperationLog() {
    }

	
    public NodeOperationLog(long operationLogId) {
        this.operationLogId = operationLogId;
    }
    public NodeOperationLog(long operationLogId, NodeOperation nodeOperation, String transId, String userName, String requestorIp, String suppliedTransId, String token, String nodeAddress, String returnUrl, String serviceType, Date startDttm, Date endDttm, String hostName, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy, Set<NodeOperationLogStatus> nodeOperationLogStatuses, Set<NodeOperationLogParameter> nodeOperationLogParameters) {
       this.operationLogId = operationLogId;
       this.nodeOperation = nodeOperation;
       this.transId = transId;
       this.userName = userName;
       this.requestorIp = requestorIp;
       this.suppliedTransId = suppliedTransId;
       this.token = token;
       this.nodeAddress = nodeAddress;
       this.returnUrl = returnUrl;
       this.serviceType = serviceType;
       this.startDttm = startDttm;
       this.endDttm = endDttm;
       this.hostName = hostName;
       this.createdDttm = createdDttm;
       this.createdBy = createdBy;
       this.updatedDttm = updatedDttm;
       this.updatedBy = updatedBy;
       this.nodeOperationLogStatuses = nodeOperationLogStatuses;
       this.nodeOperationLogParameters = nodeOperationLogParameters;
    }
   
    public long getOperationLogId() {
        return this.operationLogId;
    }
    
    public void setOperationLogId(long operationLogId) {
        this.operationLogId = operationLogId;
    }
    public NodeOperation getNodeOperation() {
        return this.nodeOperation;
    }
    
    public void setNodeOperation(NodeOperation nodeOperation) {
        this.nodeOperation = nodeOperation;
    }
    public String getTransId() {
        return this.transId;
    }
    
    public void setTransId(String transId) {
        this.transId = transId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getRequestorIp() {
        return this.requestorIp;
    }
    
    public void setRequestorIp(String requestorIp) {
        this.requestorIp = requestorIp;
    }
    public String getSuppliedTransId() {
        return this.suppliedTransId;
    }
    
    public void setSuppliedTransId(String suppliedTransId) {
        this.suppliedTransId = suppliedTransId;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public String getNodeAddress() {
        return this.nodeAddress;
    }
    
    public void setNodeAddress(String nodeAddress) {
        this.nodeAddress = nodeAddress;
    }
    public String getReturnUrl() {
        return this.returnUrl;
    }
    
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl;
    }
    public String getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }
    public Date getStartDttm() {
        return this.startDttm;
    }
    
    public void setStartDttm(Date startDttm) {
        this.startDttm = startDttm;
    }
    public Date getEndDttm() {
        return this.endDttm;
    }
    
    public void setEndDttm(Date endDttm) {
        this.endDttm = endDttm;
    }
    public String getHostName() {
        return this.hostName;
    }
    
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }
    public Date getCreatedDttm() {
        return this.createdDttm;
    }
    
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }
    
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<NodeOperationLogStatus> getNodeOperationLogStatuses() {
        return this.nodeOperationLogStatuses;
    }
    
    public void setNodeOperationLogStatuses(Set<NodeOperationLogStatus> nodeOperationLogStatuses) {
        this.nodeOperationLogStatuses = nodeOperationLogStatuses;
    }
    public Set<NodeOperationLogParameter> getNodeOperationLogParameters() {
        return this.nodeOperationLogParameters;
    }
    
    public void setNodeOperationLogParameters(Set<NodeOperationLogParameter> nodeOperationLogParameters) {
        this.nodeOperationLogParameters = nodeOperationLogParameters;
    }




}


