package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * NodeProcessMonitor generated by hbm2java
 */
public class NodeProcessMonitor  implements java.io.Serializable {


     private long pid;
     private String transactionId;
     private Long operationId;
     private String processName;
     private String processStatus;
     private Date updatedDttm;
     private String updatedBy;
     private String nodeAddress;

    public NodeProcessMonitor() {
    }

	
    public NodeProcessMonitor(long pid) {
        this.pid = pid;
    }
    public NodeProcessMonitor(long pid, String transactionId, Long operationId, String processName, String processStatus, Date updatedDttm, String updatedBy, String nodeAddress) {
       this.pid = pid;
       this.transactionId = transactionId;
       this.operationId = operationId;
       this.processName = processName;
       this.processStatus = processStatus;
       this.updatedDttm = updatedDttm;
       this.updatedBy = updatedBy;
       this.nodeAddress = nodeAddress;
    }
   
    public long getPid() {
        return this.pid;
    }
    
    public void setPid(long pid) {
        this.pid = pid;
    }
    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }
    public Long getOperationId() {
        return this.operationId;
    }
    
    public void setOperationId(Long operationId) {
        this.operationId = operationId;
    }
    public String getProcessName() {
        return this.processName;
    }
    
    public void setProcessName(String processName) {
        this.processName = processName;
    }
    public String getProcessStatus() {
        return this.processStatus;
    }
    
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus;
    }
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }
    
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public String getNodeAddress() {
        return this.nodeAddress;
    }
    
    public void setNodeAddress(String nodeAddress) {
        this.nodeAddress = nodeAddress;
    }




}


