package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NodeFileCabin generated by hbm2java
 */
public class NodeFileCabin  implements java.io.Serializable {


     private long fileId;
     private String transId;
     private String fileName;
     private String fileType;
     private String statusCd;
     private String dataflowName;
     private String submitUrl;
     private String submitToken;
     private Date submitDttm;
     private Blob fileContent;
     private Long fileSize;
     private Date createdDttm;
     private String createdBy;
     private Date updatedDttm;
     private String updatedBy;
     private String documentId;
     private Set<RcraSub> rcraSubs = new HashSet<RcraSub>(0);

    public NodeFileCabin() {
    }

	
    public NodeFileCabin(long fileId, String transId, Date createdDttm, String createdBy) {
        this.fileId = fileId;
        this.transId = transId;
        this.createdDttm = createdDttm;
        this.createdBy = createdBy;
    }
    public NodeFileCabin(long fileId, String transId, String fileName, String fileType, String statusCd, String dataflowName, String submitUrl, String submitToken, Date submitDttm, Blob fileContent, Long fileSize, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy, String documentId, Set<RcraSub> rcraSubs) {
       this.fileId = fileId;
       this.transId = transId;
       this.fileName = fileName;
       this.fileType = fileType;
       this.statusCd = statusCd;
       this.dataflowName = dataflowName;
       this.submitUrl = submitUrl;
       this.submitToken = submitToken;
       this.submitDttm = submitDttm;
       this.fileContent = fileContent;
       this.fileSize = fileSize;
       this.createdDttm = createdDttm;
       this.createdBy = createdBy;
       this.updatedDttm = updatedDttm;
       this.updatedBy = updatedBy;
       this.documentId = documentId;
       this.rcraSubs = rcraSubs;
    }
   
    public long getFileId() {
        return this.fileId;
    }
    
    public void setFileId(long fileId) {
        this.fileId = fileId;
    }
    public String getTransId() {
        return this.transId;
    }
    
    public void setTransId(String transId) {
        this.transId = transId;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    public String getDataflowName() {
        return this.dataflowName;
    }
    
    public void setDataflowName(String dataflowName) {
        this.dataflowName = dataflowName;
    }
    public String getSubmitUrl() {
        return this.submitUrl;
    }
    
    public void setSubmitUrl(String submitUrl) {
        this.submitUrl = submitUrl;
    }
    public String getSubmitToken() {
        return this.submitToken;
    }
    
    public void setSubmitToken(String submitToken) {
        this.submitToken = submitToken;
    }
    public Date getSubmitDttm() {
        return this.submitDttm;
    }
    
    public void setSubmitDttm(Date submitDttm) {
        this.submitDttm = submitDttm;
    }
    public Blob getFileContent() {
        return this.fileContent;
    }
    
    public void setFileContent(Blob fileContent) {
        this.fileContent = fileContent;
    }
    public Long getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }
    public Date getCreatedDttm() {
        return this.createdDttm;
    }
    
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }
    
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public String getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }
    public Set<RcraSub> getRcraSubs() {
        return this.rcraSubs;
    }
    
    public void setRcraSubs(Set<RcraSub> rcraSubs) {
        this.rcraSubs = rcraSubs;
    }




}


