package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * NodeAccountType generated by hbm2java
 */
public class NodeAccountType  implements java.io.Serializable {


     private long accountTypeId;
     private String accountType;
     private String accountDesc;
     private Set<NodeAccountTypeXref> nodeAccountTypeXrefs = new HashSet<NodeAccountTypeXref>(0);

    public NodeAccountType() {
    }

	
    public NodeAccountType(long accountTypeId) {
        this.accountTypeId = accountTypeId;
    }
    public NodeAccountType(long accountTypeId, String accountType, String accountDesc, Set<NodeAccountTypeXref> nodeAccountTypeXrefs) {
       this.accountTypeId = accountTypeId;
       this.accountType = accountType;
       this.accountDesc = accountDesc;
       this.nodeAccountTypeXrefs = nodeAccountTypeXrefs;
    }
   
    public long getAccountTypeId() {
        return this.accountTypeId;
    }
    
    public void setAccountTypeId(long accountTypeId) {
        this.accountTypeId = accountTypeId;
    }
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }
    public String getAccountDesc() {
        return this.accountDesc;
    }
    
    public void setAccountDesc(String accountDesc) {
        this.accountDesc = accountDesc;
    }
    public Set<NodeAccountTypeXref> getNodeAccountTypeXrefs() {
        return this.nodeAccountTypeXrefs;
    }
    
    public void setNodeAccountTypeXrefs(Set<NodeAccountTypeXref> nodeAccountTypeXrefs) {
        this.nodeAccountTypeXrefs = nodeAccountTypeXrefs;
    }




}


