package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.sql.Blob;
import java.util.Date;

/**
 * NodeOperationManager generated by hbm2java
 */
public class NodeOperationManager  implements java.io.Serializable {


     private long submitId;
     private String operationName;
     private String statusCd;
     private Date submittedDttm;
     private String submittedUrl;
     private String versionNo;
     private String transId;
     private String suppliedTransId;
     private Blob fileContent;
     private String dataFlow;

    public NodeOperationManager() {
    }

	
    public NodeOperationManager(long submitId) {
        this.submitId = submitId;
    }
    public NodeOperationManager(long submitId, String operationName, String statusCd, Date submittedDttm, String submittedUrl, String versionNo, String transId, String suppliedTransId, Blob fileContent, String dataFlow) {
       this.submitId = submitId;
       this.operationName = operationName;
       this.statusCd = statusCd;
       this.submittedDttm = submittedDttm;
       this.submittedUrl = submittedUrl;
       this.versionNo = versionNo;
       this.transId = transId;
       this.suppliedTransId = suppliedTransId;
       this.fileContent = fileContent;
       this.dataFlow = dataFlow;
    }
   
    public long getSubmitId() {
        return this.submitId;
    }
    
    public void setSubmitId(long submitId) {
        this.submitId = submitId;
    }
    public String getOperationName() {
        return this.operationName;
    }
    
    public void setOperationName(String operationName) {
        this.operationName = operationName;
    }
    public String getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }
    public Date getSubmittedDttm() {
        return this.submittedDttm;
    }
    
    public void setSubmittedDttm(Date submittedDttm) {
        this.submittedDttm = submittedDttm;
    }
    public String getSubmittedUrl() {
        return this.submittedUrl;
    }
    
    public void setSubmittedUrl(String submittedUrl) {
        this.submittedUrl = submittedUrl;
    }
    public String getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(String versionNo) {
        this.versionNo = versionNo;
    }
    public String getTransId() {
        return this.transId;
    }
    
    public void setTransId(String transId) {
        this.transId = transId;
    }
    public String getSuppliedTransId() {
        return this.suppliedTransId;
    }
    
    public void setSuppliedTransId(String suppliedTransId) {
        this.suppliedTransId = suppliedTransId;
    }
    public Blob getFileContent() {
        return this.fileContent;
    }
    
    public void setFileContent(Blob fileContent) {
        this.fileContent = fileContent;
    }
    public String getDataFlow() {
        return this.dataFlow;
    }
    
    public void setDataFlow(String dataFlow) {
        this.dataFlow = dataFlow;
    }




}


