package com.enfotech.rest.domain.node;

// Generated Oct 3, 2013 4:48:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * RcraSubDtl generated by hbm2java
 */
public class RcraSubDtl implements java.io.Serializable {

	private RcraSubDtlId id;
	private RcraSub rcraSub;

	public RcraSubDtl() {
	}

	public RcraSubDtl(RcraSubDtlId id, RcraSub rcraSub) {
		this.id = id;
		this.rcraSub = rcraSub;
	}

	public RcraSubDtlId getId() {
		return this.id;
	}

	public void setId(RcraSubDtlId id) {
		this.id = id;
	}

	public RcraSub getRcraSub() {
		return this.rcraSub;
	}

	public void setRcraSub(RcraSub rcraSub) {
		this.rcraSub = rcraSub;
	}

}
