package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * SysSequenceNo generated by hbm2java
 */
public class SysSequenceNo  implements java.io.Serializable {


     private long sequenceId;
     private String tableName;
     private String columnName;
     private Integer minNumber;
     private Long maxNumber;
     private Long lastUsedNumber;
     private Character statusCd;
     private Date createdDttm;
     private String createdBy;
     private Date updatedDttm;
     private String updatedBy;

    public SysSequenceNo() {
    }

	
    public SysSequenceNo(long sequenceId) {
        this.sequenceId = sequenceId;
    }
    public SysSequenceNo(long sequenceId, String tableName, String columnName, Integer minNumber, Long maxNumber, Long lastUsedNumber, Character statusCd, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy) {
       this.sequenceId = sequenceId;
       this.tableName = tableName;
       this.columnName = columnName;
       this.minNumber = minNumber;
       this.maxNumber = maxNumber;
       this.lastUsedNumber = lastUsedNumber;
       this.statusCd = statusCd;
       this.createdDttm = createdDttm;
       this.createdBy = createdBy;
       this.updatedDttm = updatedDttm;
       this.updatedBy = updatedBy;
    }
   
    public long getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(long sequenceId) {
        this.sequenceId = sequenceId;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
    public Integer getMinNumber() {
        return this.minNumber;
    }
    
    public void setMinNumber(Integer minNumber) {
        this.minNumber = minNumber;
    }
    public Long getMaxNumber() {
        return this.maxNumber;
    }
    
    public void setMaxNumber(Long maxNumber) {
        this.maxNumber = maxNumber;
    }
    public Long getLastUsedNumber() {
        return this.lastUsedNumber;
    }
    
    public void setLastUsedNumber(Long lastUsedNumber) {
        this.lastUsedNumber = lastUsedNumber;
    }
    public Character getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(Character statusCd) {
        this.statusCd = statusCd;
    }
    public Date getCreatedDttm() {
        return this.createdDttm;
    }
    
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }
    
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


