package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * SysUserPagelayout generated by hbm2java
 */
public class SysUserPagelayout  implements java.io.Serializable {


     private long userId;
     private SysUserInfo sysUserInfo;
     private String columns;
     private Date createdDttm;
     private String createdBy;
     private Date updatedDttm;
     private String updatedBy;

    public SysUserPagelayout() {
    }

	
    public SysUserPagelayout(SysUserInfo sysUserInfo, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy) {
        this.sysUserInfo = sysUserInfo;
        this.createdDttm = createdDttm;
        this.createdBy = createdBy;
        this.updatedDttm = updatedDttm;
        this.updatedBy = updatedBy;
    }
    public SysUserPagelayout(SysUserInfo sysUserInfo, String columns, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy) {
       this.sysUserInfo = sysUserInfo;
       this.columns = columns;
       this.createdDttm = createdDttm;
       this.createdBy = createdBy;
       this.updatedDttm = updatedDttm;
       this.updatedBy = updatedBy;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public SysUserInfo getSysUserInfo() {
        return this.sysUserInfo;
    }
    
    public void setSysUserInfo(SysUserInfo sysUserInfo) {
        this.sysUserInfo = sysUserInfo;
    }
    public String getColumns() {
        return this.columns;
    }
    
    public void setColumns(String columns) {
        this.columns = columns;
    }
    public Date getCreatedDttm() {
        return this.createdDttm;
    }
    
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }
    
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}


