package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0



/**
 * SysUserAddressId generated by hbm2java
 */
public class SysUserAddressId  implements java.io.Serializable {


     private long addressId;
     private long userId;

    public SysUserAddressId() {
    }

    public SysUserAddressId(long addressId, long userId) {
       this.addressId = addressId;
       this.userId = userId;
    }
   
    public long getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(long addressId) {
        this.addressId = addressId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysUserAddressId) ) return false;
		 SysUserAddressId castOther = ( SysUserAddressId ) other; 
         
		 return (this.getAddressId()==castOther.getAddressId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getAddressId();
         result = 37 * result + (int) this.getUserId();
         return result;
   }   


}


