package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysUserInfo generated by hbm2java
 */
public class SysUserInfo  implements java.io.Serializable {


     private long userId;
     private String lastName;
     private String firstName;
     private Character middleInitial;
     private String loginName;
     private String loginPassword;
     private String userStatusCd;
     private String last4Ssn;
     private String changePwdFlag;
     private String phoneNumber;
     private String comments;
     private Date createdDttm;
     private String createdBy;
     private Date updatedDttm;
     private String updatedBy;
     private Set<NodeAccountTypeXref> nodeAccountTypeXrefs = new HashSet<NodeAccountTypeXref>(0);
     private SysUserPagelayout sysUserPagelayout;
     private Set<SysEmail> sysEmails = new HashSet<SysEmail>(0);
     private Set<NodeOperation> nodeOperations = new HashSet<NodeOperation>(0);
     private Set<SysUserAddress> sysUserAddresses = new HashSet<SysUserAddress>(0);

    public SysUserInfo() {
    }

	
    public SysUserInfo(long userId, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy) {
        this.userId = userId;
        this.createdDttm = createdDttm;
        this.createdBy = createdBy;
        this.updatedDttm = updatedDttm;
        this.updatedBy = updatedBy;
    }
    public SysUserInfo(long userId, String lastName, String firstName, Character middleInitial, String loginName, String loginPassword, String userStatusCd, String last4Ssn, String changePwdFlag, String phoneNumber, String comments, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy, Set<NodeAccountTypeXref> nodeAccountTypeXrefs, SysUserPagelayout sysUserPagelayout, Set<SysEmail> sysEmails, Set<NodeOperation> nodeOperations, Set<SysUserAddress> sysUserAddresses) {
       this.userId = userId;
       this.lastName = lastName;
       this.firstName = firstName;
       this.middleInitial = middleInitial;
       this.loginName = loginName;
       this.loginPassword = loginPassword;
       this.userStatusCd = userStatusCd;
       this.last4Ssn = last4Ssn;
       this.changePwdFlag = changePwdFlag;
       this.phoneNumber = phoneNumber;
       this.comments = comments;
       this.createdDttm = createdDttm;
       this.createdBy = createdBy;
       this.updatedDttm = updatedDttm;
       this.updatedBy = updatedBy;
       this.nodeAccountTypeXrefs = nodeAccountTypeXrefs;
       this.sysUserPagelayout = sysUserPagelayout;
       this.sysEmails = sysEmails;
       this.nodeOperations = nodeOperations;
       this.sysUserAddresses = sysUserAddresses;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public Character getMiddleInitial() {
        return this.middleInitial;
    }
    
    public void setMiddleInitial(Character middleInitial) {
        this.middleInitial = middleInitial;
    }
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public String getLoginPassword() {
        return this.loginPassword;
    }
    
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }
    public String getUserStatusCd() {
        return this.userStatusCd;
    }
    
    public void setUserStatusCd(String userStatusCd) {
        this.userStatusCd = userStatusCd;
    }
    public String getLast4Ssn() {
        return this.last4Ssn;
    }
    
    public void setLast4Ssn(String last4Ssn) {
        this.last4Ssn = last4Ssn;
    }
    public String getChangePwdFlag() {
        return this.changePwdFlag;
    }
    
    public void setChangePwdFlag(String changePwdFlag) {
        this.changePwdFlag = changePwdFlag;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Date getCreatedDttm() {
        return this.createdDttm;
    }
    
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }
    
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<NodeAccountTypeXref> getNodeAccountTypeXrefs() {
        return this.nodeAccountTypeXrefs;
    }
    
    public void setNodeAccountTypeXrefs(Set<NodeAccountTypeXref> nodeAccountTypeXrefs) {
        this.nodeAccountTypeXrefs = nodeAccountTypeXrefs;
    }
    public SysUserPagelayout getSysUserPagelayout() {
        return this.sysUserPagelayout;
    }
    
    public void setSysUserPagelayout(SysUserPagelayout sysUserPagelayout) {
        this.sysUserPagelayout = sysUserPagelayout;
    }
    public Set<SysEmail> getSysEmails() {
        return this.sysEmails;
    }
    
    public void setSysEmails(Set<SysEmail> sysEmails) {
        this.sysEmails = sysEmails;
    }
    public Set<NodeOperation> getNodeOperations() {
        return this.nodeOperations;
    }
    
    public void setNodeOperations(Set<NodeOperation> nodeOperations) {
        this.nodeOperations = nodeOperations;
    }
    public Set<SysUserAddress> getSysUserAddresses() {
        return this.sysUserAddresses;
    }
    
    public void setSysUserAddresses(Set<SysUserAddress> sysUserAddresses) {
        this.sysUserAddresses = sysUserAddresses;
    }




}


