package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * NodeWebService generated by hbm2java
 */
public class NodeWebService  implements java.io.Serializable {


     private long webServiceId;
     private String webServiceName;
     private String webServiceDesc;
     private Set<NodeOperation> nodeOperations = new HashSet<NodeOperation>(0);
     private Set<NodeDomain> nodeDomains = new HashSet<NodeDomain>(0);

    public NodeWebService() {
    }

	
    public NodeWebService(long webServiceId) {
        this.webServiceId = webServiceId;
    }
    public NodeWebService(long webServiceId, String webServiceName, String webServiceDesc, Set<NodeOperation> nodeOperations, Set<NodeDomain> nodeDomains) {
       this.webServiceId = webServiceId;
       this.webServiceName = webServiceName;
       this.webServiceDesc = webServiceDesc;
       this.nodeOperations = nodeOperations;
       this.nodeDomains = nodeDomains;
    }
   
    public long getWebServiceId() {
        return this.webServiceId;
    }
    
    public void setWebServiceId(long webServiceId) {
        this.webServiceId = webServiceId;
    }
    public String getWebServiceName() {
        return this.webServiceName;
    }
    
    public void setWebServiceName(String webServiceName) {
        this.webServiceName = webServiceName;
    }
    public String getWebServiceDesc() {
        return this.webServiceDesc;
    }
    
    public void setWebServiceDesc(String webServiceDesc) {
        this.webServiceDesc = webServiceDesc;
    }
    public Set<NodeOperation> getNodeOperations() {
        return this.nodeOperations;
    }
    
    public void setNodeOperations(Set<NodeOperation> nodeOperations) {
        this.nodeOperations = nodeOperations;
    }
    public Set<NodeDomain> getNodeDomains() {
        return this.nodeDomains;
    }
    
    public void setNodeDomains(Set<NodeDomain> nodeDomains) {
        this.nodeDomains = nodeDomains;
    }




}


