package com.enfotech.rest.domain.node;

// Generated Oct 3, 2013 4:48:47 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RcraSub generated by hbm2java
 */
public class RcraSub implements java.io.Serializable {

	private BigDecimal rcraSubId;
	private NodeFileCabin nodeFileCabin;
	private Date startDate;
	private Date endDate;
	private Clob errorRpt;
	private Set rcraSubDtls = new HashSet(0);

	public RcraSub() {
	}

	public RcraSub(BigDecimal rcraSubId) {
		this.rcraSubId = rcraSubId;
	}

	public RcraSub(BigDecimal rcraSubId, NodeFileCabin nodeFileCabin,
			Date startDate, Date endDate, Clob errorRpt, Set rcraSubDtls) {
		this.rcraSubId = rcraSubId;
		this.nodeFileCabin = nodeFileCabin;
		this.startDate = startDate;
		this.endDate = endDate;
		this.errorRpt = errorRpt;
		this.rcraSubDtls = rcraSubDtls;
	}

	public BigDecimal getRcraSubId() {
		return this.rcraSubId;
	}

	public void setRcraSubId(BigDecimal rcraSubId) {
		this.rcraSubId = rcraSubId;
	}

	public NodeFileCabin getNodeFileCabin() {
		return this.nodeFileCabin;
	}

	public void setNodeFileCabin(NodeFileCabin nodeFileCabin) {
		this.nodeFileCabin = nodeFileCabin;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Clob getErrorRpt() {
		return this.errorRpt;
	}

	public void setErrorRpt(Clob errorRpt) {
		this.errorRpt = errorRpt;
	}

	public Set getRcraSubDtls() {
		return this.rcraSubDtls;
	}

	public void setRcraSubDtls(Set rcraSubDtls) {
		this.rcraSubDtls = rcraSubDtls;
	}

}
