package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SysAddress generated by hbm2java
 */
public class SysAddress  implements java.io.Serializable {


     private long addressId;
     private String address;
     private String supplementalAddress;
     private String localityName;
     private String stateCd;
     private String zipCode;
     private String countryCd;
     private Character statusCd;
     private String addressDesc;
     private Date createdDttm;
     private String createdBy;
     private Date updatedDttm;
     private String updatedBy;
     private Set<SysUserAddress> sysUserAddresses = new HashSet<SysUserAddress>(0);

    public SysAddress() {
    }

	
    public SysAddress(long addressId, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy) {
        this.addressId = addressId;
        this.createdDttm = createdDttm;
        this.createdBy = createdBy;
        this.updatedDttm = updatedDttm;
        this.updatedBy = updatedBy;
    }
    public SysAddress(long addressId, String address, String supplementalAddress, String localityName, String stateCd, String zipCode, String countryCd, Character statusCd, String addressDesc, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy, Set<SysUserAddress> sysUserAddresses) {
       this.addressId = addressId;
       this.address = address;
       this.supplementalAddress = supplementalAddress;
       this.localityName = localityName;
       this.stateCd = stateCd;
       this.zipCode = zipCode;
       this.countryCd = countryCd;
       this.statusCd = statusCd;
       this.addressDesc = addressDesc;
       this.createdDttm = createdDttm;
       this.createdBy = createdBy;
       this.updatedDttm = updatedDttm;
       this.updatedBy = updatedBy;
       this.sysUserAddresses = sysUserAddresses;
    }
   
    public long getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(long addressId) {
        this.addressId = addressId;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getSupplementalAddress() {
        return this.supplementalAddress;
    }
    
    public void setSupplementalAddress(String supplementalAddress) {
        this.supplementalAddress = supplementalAddress;
    }
    public String getLocalityName() {
        return this.localityName;
    }
    
    public void setLocalityName(String localityName) {
        this.localityName = localityName;
    }
    public String getStateCd() {
        return this.stateCd;
    }
    
    public void setStateCd(String stateCd) {
        this.stateCd = stateCd;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getCountryCd() {
        return this.countryCd;
    }
    
    public void setCountryCd(String countryCd) {
        this.countryCd = countryCd;
    }
    public Character getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(Character statusCd) {
        this.statusCd = statusCd;
    }
    public String getAddressDesc() {
        return this.addressDesc;
    }
    
    public void setAddressDesc(String addressDesc) {
        this.addressDesc = addressDesc;
    }
    public Date getCreatedDttm() {
        return this.createdDttm;
    }
    
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }
    
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<SysUserAddress> getSysUserAddresses() {
        return this.sysUserAddresses;
    }
    
    public void setSysUserAddresses(Set<SysUserAddress> sysUserAddresses) {
        this.sysUserAddresses = sysUserAddresses;
    }




}


