package com.enfotech.rest.domain.node;
// Generated Oct 11, 2013 2:00:01 PM by Hibernate Tools 3.6.0


import java.sql.Clob;
import java.util.Date;

/**
 * SysConfig generated by hbm2java
 */
public class SysConfig  implements java.io.Serializable {


     private long configId;
     private String configName;
     private Clob configXml;
     private String configTypeCd;
     private Character statusCd;
     private Date createdDttm;
     private String createdBy;
     private Date updatedDttm;
     private String updatedBy;
     private Clob configClob;

    public SysConfig() {
    }

	
    public SysConfig(long configId) {
        this.configId = configId;
    }
    public SysConfig(long configId, String configName, Clob configXml, String configTypeCd, Character statusCd, Date createdDttm, String createdBy, Date updatedDttm, String updatedBy, Clob configClob) {
       this.configId = configId;
       this.configName = configName;
       this.configXml = configXml;
       this.configTypeCd = configTypeCd;
       this.statusCd = statusCd;
       this.createdDttm = createdDttm;
       this.createdBy = createdBy;
       this.updatedDttm = updatedDttm;
       this.updatedBy = updatedBy;
       this.configClob = configClob;
    }
   
    public long getConfigId() {
        return this.configId;
    }
    
    public void setConfigId(long configId) {
        this.configId = configId;
    }
    public String getConfigName() {
        return this.configName;
    }
    
    public void setConfigName(String configName) {
        this.configName = configName;
    }
    public Clob getConfigXml() {
        return this.configXml;
    }
    
    public void setConfigXml(Clob configXml) {
        this.configXml = configXml;
    }
    public String getConfigTypeCd() {
        return this.configTypeCd;
    }
    
    public void setConfigTypeCd(String configTypeCd) {
        this.configTypeCd = configTypeCd;
    }
    public Character getStatusCd() {
        return this.statusCd;
    }
    
    public void setStatusCd(Character statusCd) {
        this.statusCd = statusCd;
    }
    public Date getCreatedDttm() {
        return this.createdDttm;
    }
    
    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }
    
    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Clob getConfigClob() {
        return this.configClob;
    }
    
    public void setConfigClob(Clob configClob) {
        this.configClob = configClob;
    }




}


